# Generated by Django 5.2.7 on 2025-10-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("sub_name", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("centroid_lat", models.FloatField()),
                ("centroid_lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="AreaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("representation", models.CharField(max_length=7)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DiaryPrecipitationClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lower_limmit", models.FloatField(blank=True, null=True)),
                ("upper_limmit", models.FloatField(blank=True, null=True)),
                ("classification", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "research_diaryprecipitationclassification",
            },
        ),
        migrations.CreateModel(
            name="PluviometerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AreaNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("step", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.area",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="area_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="business_app.areatype",
            ),
        ),
        migrations.CreateModel(
            name="Pluviometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("msnm", models.IntegerField(blank=True, null=True)),
                (
                    "pluviometer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="business_app.pluviometertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecipitationConcentrationIndexByArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_considered", models.PositiveSmallIntegerField()),
                ("a_value", models.FloatField()),
                ("b_value", models.FloatField()),
                ("r_2_value", models.FloatField()),
                ("ci_value", models.FloatField()),
                ("rainy_days", models.PositiveIntegerField()),
                ("max_rain_value", models.FloatField()),
                ("rainy_days_percent", models.FloatField()),
                ("rain_by_period_avg", models.FloatField()),
                ("rainy_days_by_period_avg", models.TextField()),
                ("total_rain_value", models.FloatField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecipitationConcentrationIndexByPluviometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_considered", models.PositiveSmallIntegerField()),
                ("a_value", models.FloatField()),
                ("b_value", models.FloatField()),
                ("r_2_value", models.FloatField()),
                ("ci_value", models.FloatField()),
                ("rainy_days", models.PositiveIntegerField()),
                ("total_rain_value", models.FloatField()),
                ("max_rain_value", models.FloatField()),
                ("rainy_days_percent", models.FloatField()),
                ("rain_by_period_avg", models.FloatField()),
                ("rainy_days_by_period_avg", models.TextField()),
                (
                    "pluviometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.pluviometer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecipitationConcentrationIndexMonthlyByArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_considered", models.PositiveSmallIntegerField()),
                ("a_value", models.FloatField()),
                ("b_value", models.FloatField()),
                ("r_2_value", models.FloatField()),
                ("ci_value", models.FloatField()),
                ("rainy_days", models.PositiveIntegerField()),
                ("max_rain_value", models.FloatField()),
                ("rainy_days_percent", models.FloatField()),
                ("rain_by_period_avg", models.FloatField()),
                ("rainy_days_by_period_avg", models.TextField()),
                ("month", models.PositiveSmallIntegerField()),
                ("total_rain_value", models.FloatField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecipitationConcentrationIndexMonthlyByPluviometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_considered", models.PositiveSmallIntegerField()),
                ("a_value", models.FloatField()),
                ("b_value", models.FloatField()),
                ("r_2_value", models.FloatField()),
                ("ci_value", models.FloatField()),
                ("rainy_days", models.PositiveIntegerField()),
                ("max_rain_value", models.FloatField()),
                ("rainy_days_percent", models.FloatField()),
                ("rain_by_period_avg", models.FloatField()),
                ("rainy_days_by_period_avg", models.TextField()),
                ("month", models.PositiveSmallIntegerField()),
                ("total_rain_value", models.FloatField()),
                (
                    "pluviometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.pluviometer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_date", models.DateField()),
                ("rain_value", models.FloatField()),
                (
                    "pluviometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.pluviometer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_precipit", models.FloatField()),
                ("max_registered_value", models.FloatField()),
                ("daily_mean", models.FloatField()),
                ("rainy_days_count", models.PositiveIntegerField()),
                ("rainy_streak_count", models.IntegerField()),
                ("rainy_streak_med_long", models.FloatField()),
                ("year", models.SmallIntegerField()),
                (
                    "pluviometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.pluviometer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_registered_value", models.FloatField()),
                ("daily_mean", models.FloatField()),
                ("rainy_days_count", models.PositiveIntegerField()),
                ("rainy_streak_count", models.IntegerField()),
                ("rainy_streak_med_long", models.FloatField()),
                ("standard_deviation", models.FloatField()),
                ("variance", models.FloatField()),
                ("month", models.PositiveSmallIntegerField()),
                ("total_precipit", models.FloatField()),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.yearstatistics",
                    ),
                ),
            ],
        ),
    ]
