# Generated by Django 5.2.7 on 2025-10-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0002_alter_area_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluviometerArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.area",
                    ),
                ),
                (
                    "pluviometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.pluviometer",
                    ),
                ),
            ],
        ),
    ]
