# Generated by Django 5.2.7 on 2025-11-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0006_creating_hidrogeological_area_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluviometerarea",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pluviometer_area",
                to="business_app.area",
            ),
        ),
        migrations.AlterField(
            model_name="pluviometerarea",
            name="pluviometer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pluviometer_area",
                to="business_app.pluviometer",
            ),
        ),
    ]
