# Generated by Django 5.1.1 on 2024-09-13 04:01

from django.db import migrations


def create_superuser(apps, schema_editor):
    SystemUser = apps.get_model("users_app", "SystemUser")
    SystemUser.objects.create_user(
        username="admin",
        password="1qazxsw2",
        first_name="Admin",
        last_name="Generic",
        email="admin@commonuser.com",
        # identification_number="000000000000",
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )
    print()
    print(bcolors.OKCYAN + "SuperAdmin creado exitosamente")
    print(bcolors.OKBLUE + "Usuario:" + bcolors.OKGREEN + "admin")
    print(bcolors.OKBLUE + "Password:" + bcolors.OKGREEN + "1......2")


class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
